name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:5.2.3-bionic
    steps:
    - uses: actions/checkout@v2

    - name: Donwload ps4libdoc branch 5.05
      run: |
        git clone --depth 1  https://github.com/idc/ps4libdoc -b 5.05

    - name: Compile project (in Release)
      run: |
        swift build -c release
    
    - name: Run project
      run: |
        ./.build/release/orbis-parser
    
    - uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      with:
        name: libs
        path: output/