name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install libyaml-dev
      run: |
        sudo apt-get update
        sudo apt-get -y install libyaml-dev

    - name: Compile project
      run: |
        make all