name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:5.2.3-bionic
    steps:
    - uses: actions/checkout@v2

    - name: Donwload ps4libdoc branch 5.05
      run: |
        git clone --depth 1  https://github.com/idc/ps4libdoc -b 5.05

    - name: Compile project (in Release)
      run: |
        swift build -c release
    
    - name: Run project
      run: |
        ./.build/release/orbis-parser
    
    - uses: actions/upload-artifact@v2
      with:
        name: libs
        path: output/

    - name: Create tag name
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        export TAGNAME="snapshot_$(date +'%Y_%m_%d_%H%M%S')"
        echo "::set-env name=NEW_TAGNAME::$TAGNAME"
    
    - name: Use tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        export TAGNAME="$(echo ${GITHUB_REF##*/})"
        echo "::set-env name=NEW_TAGNAME::$TAGNAME"
    
    - name: Prepare Release
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      run: |
        tar -zcvf libs.tar.gz output
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: libs.tar.gz
        tag_name: ${{ env.NEW_TAGNAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}